<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Permiso;

class PermisosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permisos = [
            [
                'nombre' => 'Crear Domicilio',
                'descripcion' => 'Permite la creación de nuevos registros de domicilios en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Domicilio',
                'descripcion' => 'Permite la visualización de registros de domicilios en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Domicilio',
                'descripcion' => 'Permite la edición de los registros de domicilios existentes en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Domicilio',
                'descripcion' => 'Permite la eliminación de registros de domicilios en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Persona',
                'descripcion' => 'Permite la creación de nuevos registros de personas en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Persona',
                'descripcion' => 'Permite la visualización de registros de personas existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Persona',
                'descripcion' => 'Permite la edición de los registros de personas existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Persona',
                'descripcion' => 'Permite la eliminación de registros de personas del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Usuario',
                'descripcion' => 'Permite la creación de nuevos usuarios en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Usuario',
                'descripcion' => 'Permite la eliminación de usuarios del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Usuario',
                'descripcion' => 'Permite la visualización de usuarios existentes en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Usuario',
                'descripcion' => 'Permite la edición de los registros de usuarios existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Tabla de Autorizaciones',
                'descripcion' => 'Permite el acceso y la gestión de la tabla de autorizaciones del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Trabajador',
                'descripcion' => 'Permite la creación de nuevos registros de trabajadores.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Trabajador',
                'descripcion' => 'Permite la visualización de registros de trabajadores existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Trabajador',
                'descripcion' => 'Permite la edición de los registros de trabajadores existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Trabajador',
                'descripcion' => 'Permite la eliminación de registros de trabajadores del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Cargo',
                'descripcion' => 'Permite la creación de nuevos registros de cargos.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Cargo',
                'descripcion' => 'Permite la visualización de registros de cargos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Cargo',
                'descripcion' => 'Permite la edición de los registros de cargos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Cargo',
                'descripcion' => 'Permite la eliminación de registros de cargos del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Custodio',
                'descripcion' => 'Permite la creación de nuevos registros de custodios.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Custodio',
                'descripcion' => 'Permite la visualización de registros de custodios existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Custodio',
                'descripcion' => 'Permite la edición de los registros de custodios existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Custodio',
                'descripcion' => 'Permite la eliminación de registros de custodios del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Servicio',
                'descripcion' => 'Permite la creación de nuevos registros de servicios.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Servicio',
                'descripcion' => 'Permite la visualización de registros de servicios existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Servicio',
                'descripcion' => 'Permite la edición de registros de servicios existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Servicio',
                'descripcion' => 'Permite la eliminación de registros de servicios del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Tipo Servicio',
                'descripcion' => 'Permite la creación de nuevos tipos de servicios.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Tipo Servicio',
                'descripcion' => 'Permite la visualización de tipos de servicios existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Tipo Servicio',
                'descripcion' => 'Permite la edición de tipos de servicios existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Tipo Servicio',
                'descripcion' => 'Permite la eliminación de tipos de servicios del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Vehiculo',
                'descripcion' => 'Permite la creación de nuevos registros de vehículos.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Vehiculo',
                'descripcion' => 'Permite la visualización de registros de vehículos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Vehiculo',
                'descripcion' => 'Permite la edición de registros de vehículos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Vehiculo',
                'descripcion' => 'Permite la eliminación de registros de vehículos del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Viaje',
                'descripcion' => 'Permite la creación de nuevos registros de viajes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Viaje',
                'descripcion' => 'Permite la visualización de registros de viajes existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Viaje',
                'descripcion' => 'Permite la edición de registros de viajes existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Viaje',
                'descripcion' => 'Permite la eliminación de registros de viajes del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Vehiculo Mercancia',
                'descripcion' => 'Permite la creación de nuevos registros de vehículos de mercancía.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Vehiculo Mercancia',
                'descripcion' => 'Permite la visualización de registros de vehículos de mercancía existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Vehiculo Mercancia',
                'descripcion' => 'Permite la edición de registros de vehículos de mercancía existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Vehiculo Mercancia',
                'descripcion' => 'Permite la eliminación de registros de vehículos de mercancía del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Sucursal',
                'descripcion' => 'Permite la creación de nuevos registros de sucursales.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Sucursal',
                'descripcion' => 'Permite la visualización de registros de sucursales existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Sucursal',
                'descripcion' => 'Permite la edición de registros de sucursales existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Sucursal',
                'descripcion' => 'Permite la eliminación de registros de sucursales del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Tipo Vehiculo',
                'descripcion' => 'Permite la creación de nuevos tipos de vehículos.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Tipo Vehiculo',
                'descripcion' => 'Permite la visualización de tipos de vehículos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Tipo Vehiculo',
                'descripcion' => 'Permite la edición de tipos de vehículos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Tipo Vehiculo',
                'descripcion' => 'Permite la eliminación de tipos de vehículos del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Asignacion Vehiculo',
                'descripcion' => 'Permite la creación de nuevas asignaciones de vehículos.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Asignacion Vehiculo',
                'descripcion' => 'Permite la visualización de asignaciones de vehículos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Asignacion Vehiculo',
                'descripcion' => 'Permite la edición de asignaciones de vehículos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Asignacion Vehiculo',
                'descripcion' => 'Permite la eliminación de asignaciones de vehículos del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear GPS',
                'descripcion' => 'Permite la creación de nuevos registros de dispositivos GPS.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer GPS',
                'descripcion' => 'Permite la visualización de registros de dispositivos GPS existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar GPS',
                'descripcion' => 'Permite la edición de registros de dispositivos GPS existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar GPS',
                'descripcion' => 'Permite la eliminación de registros de dispositivos GPS del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Camara',
                'descripcion' => 'Permite la creación de nuevos registros de cámaras.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Camara',
                'descripcion' => 'Permite la visualización de registros de cámaras existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Camara',
                'descripcion' => 'Permite la edición de registros de cámaras existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Camara',
                'descripcion' => 'Permite la eliminación de registros de cámaras del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Detalles',
                'descripcion' => 'Permite la creación de nuevos registros de detalles.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Detalles',
                'descripcion' => 'Permite la visualización de registros de detalles existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Detalles',
                'descripcion' => 'Permite la edición de registros de detalles existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Detalles',
                'descripcion' => 'Permite la eliminación de registros de detalles del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Gastos',
                'descripcion' => 'Permite la creación de nuevos registros de gastos.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Gastos',
                'descripcion' => 'Permite la visualización de registros de gastos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Gastos',
                'descripcion' => 'Permite la edición de registros de gastos existentes.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Gastos',
                'descripcion' => 'Permite la eliminación de registros de gastos del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Crear Empresa',
                'descripcion' => 'Permite la creación de registros de empresa en el sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Leer Empresa',
                'descripcion' => 'Permite la visualización de registros de empresa del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Modificar Empresa',
                'descripcion' => 'Permite la modificación de registros de empresa del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Eliminar Empresa',
                'descripcion' => 'Permite la eliminación de registros de empresa del sistema.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Acceso a la camara',
                'descripcion' => 'Permite el acceso a la camara en tiempo real.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Acceso al gps',
                'descripcion' => 'Permite el acceso al GPS en tiempo real.',
                'estatus' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($permisos as $permiso) {
            Permiso::create($permiso);
        }
    }
}
